name: Bazel build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        bazelisk-version: "1.29.0"
    - name: Bazel build
      run: bazel build //...
          
