name: Build
on: [push]

env:
  BAZELISK_VERSION: "1.29.0"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        bazelisk-version: ${{ env.BAZELISK_VERSION }}
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
    - name: Checkout
      uses: actions/checkout@v6
    - name: Bazel build
      run: bazelisk build //...
          
